apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-demo-llm-kustomize
spec:
  destination:
    name: in-cluster
    namespace: mmikhail-demo
  project: ai-demos
  source:
    path: argocd/ai-llm-demo/kustomize/overlays/single-model
    repoURL: https://github.com/redmikhail/ai-dev01-demo.git
    targetRevision: main
