apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-demo-llm-kustomize
spec:
  destination:
    name: in-cluster
    namespace: tgis-llm-demo
  project: ai-demos
  source:
    path: argocd/ai-llm-demo/kustomize/overlays/dev
    repoURL: https://github.com/RHEcosystemAppEng/genAI-for-document-generation.git
    targetRevision: main
  # syncPolicy:
  #    automated:
  #      prune: true
